# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2f08c37fdf932f3ea7524591d3e44b86eda256f388c5cad2eaa0c6da99b18f47a84855ea9fea3d961dc01198d78475157a76c817a4f965106a52fe12f6b3d47

test:
  secret_key_base: 89aac08786657d41670a73e7f982c127dbbd30c749615a7fc4c05789e8f1ae6e02f8812750128657b303365b0d0d88dad8aae938154871573754e7b46f31ac00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
